apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-registry
    spec:
      containers:
      - name: registry
        image: registry:2
      nodeSelector:
        role: master
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
spec:
  selector:
    app: kube-registry
  ports:
  - port: 5000
  type: NodePort
